In [1]:
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine
import sys
sys.path.append('../')
from config import db_password

In [2]:
db_string = f"postgres://postgres:{db_password}@module20covid.cgcfmenzscpu.us-east-2.rds.amazonaws.com:5432/postgres"
db = create_engine(db_string)

In [3]:
q = '''
SELECT location, date, date_first_case, DATE_PART('day', date - date_first_case) AS "day_from_first_case",
total_cases, total_deaths, new_cases, new_deaths, stringency_index, population, population_density, median_age, aged_65_older, aged_70_older, 
gdp_per_capita, extreme_poverty, diabetes_prevalence, female_smokers, male_smokers, handwashing_facilities, hospital_beds_per_thousand, life_expectancy
FROM "WorldWide_Cases" ww
LEFT JOIN "Country_FirstCase" fc ON ww.iso_code = fc.iso_code
LEFT JOIN "Country_Stats" cs ON ww.iso_code = cs.iso_code
'''

dftest = pd.read_sql(sql=q, con=db)

In [4]:
dftest

,location,date,date_first_case,day_from_first_case,total_cases,total_deaths,new_cases,new_deaths,stringency_index,population,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
0,Afghanistan,2019-12-31,2019-12-31,0.0,0.0,0.0,0.0,0.0,NaN,3.892834e+07,...,2.581,1.337,1803.987,NaN,9.59,NaN,NaN,37.746,0.500,64.83
1,Afghanistan,2020-01-01,2019-12-31,1.0,0.0,0.0,0.0,0.0,0.0,3.892834e+07,...,2.581,1.337,1803.987,NaN,9.59,NaN,NaN,37.746,0.500,64.83
2,Afghanistan,2020-01-02,2019-12-31,2.0,0.0,0.0,0.0,0.0,0.0,3.892834e+07,...,2.581,1.337,1803.987,NaN,9.59,NaN,NaN,37.746,0.500,64.83
3,Afghanistan,2020-01-03,2019-12-31,3.0,0.0,0.0,0.0,0.0,0.0,3.892834e+07,...,2.581,1.337,1803.987,NaN,9.59,NaN,NaN,37.746,0.500,64.83
4,Afghanistan,2020-01-04,2019-12-31,4.0,0.0,0.0,0.0,0.0,0.0,3.892834e+07,...,2.581,1.337,1803.987,NaN,9.59,NaN,NaN,37.746,0.500,64.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31215,World,2020-07-15,2019-12-31,197.0,13300560.0,578321.0,220512.0,5657.0,NaN,7.794799e+09,...,8.696,5.355,15469.207,10.0,8.51,6.434,34.635,60.130,2.705,72.58
31216,World,2020-07-16,2019-12-31,198.0,13532281.0,583897.0,231721.0,5576.0,NaN,7.794799e+09,...,8.696,5.355,15469.207,10.0,8.51,6.434,34.635,60.130,2.705,72.58
31217,World,2020-07-17,2019-12-31,199.0,13790342.0,589700.0,258061.0,5803.0,NaN,7.794799e+09,...,8.696,5.355,15469.207,10.0,8.51,6.434,34.635,60.130,2.705,72.58
31218,World,2020-07-18,2019-12-31,200.0,14044869.0,597148.0,254527.0,7448.0,NaN,7.794799e+09,...,8.696,5.355,15469.207,10.0,8.51,6.434,34.635,60.130,2.705,72.58
31219,World,2020-07-19,2019-12-31,201.0,14267093.0,601934.0,222224.0,4786.0,NaN,7.794799e+09,...,8.696,5.355,15469.207,10.0,8.51,6.434,34.635,60.130,2.705,72.58

In [5]:
dftest.dtypes

location                              object
date                          datetime64[ns]
date_first_case               datetime64[ns]
day_from_first_case                  float64
total_cases                          float64
total_deaths                         float64
new_cases                            float64
new_deaths                           float64
stringency_index                     float64
population                           float64
population_density                   float64
median_age                           float64
aged_65_older                        float64
aged_70_older                        float64
gdp_per_capita                       float64
extreme_poverty                      float64
diabetes_prevalence                  float64
female_smokers                       float64
male_smokers                         float64
handwashing_facilities               float64
hospital_beds_per_thousand           float64
life_expectancy                      float64
dtype: object